---
name: linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-linting:
    uses: telekom-mms/.github/.github/workflows/terraform_linting.yml@313967c681dc08d00173a149633302f10b129dfc # main
